CHANGE MASTER TO
  MASTER_HOST='192.168.40.2',
  MASTER_USER='replication_user',
  MASTER_PASSWORD='bigs3cret',
  MASTER_PORT=3306,
  MASTER_LOG_FILE='primary1-bin.000002',
  MASTER_LOG_POS=1037,
  MASTER_CONNECT_RETRY=10;
CHANGE MASTER TO MASTER_USE_GTID = slave_pos;
START SLAVE;
SHOW SLAVE STATUS \G

